### ISSUE TITLE
CI Recomended Alert for Pod Restart incorrect

### ISSUE THREAD

**Issue by abdullah248** [Azure/prometheus-collector#325]
The recommended Alert for Pod Restart in https://github.com/Azure/prometheus-collector/blob/main/mixins/kubernetes/rules/recording_and_alerting_rules/templates/ci_recommended_alerts.json does not seem to be correct. 

The query is: "sum by (namespace, pod, container, cluster) (kube_pod_container_status_restarts_total{job=\"kube-state-metrics\", namespace=\"kube-system\"}) > 0"

The metric being used in the query is a counter so it will always be increasing. This means that if a pod has ever restarted it will fire forever. I think the correct approach would be using a function such as increase over a  period of time. 

Also why does the alert only restrict to pods in the kube-system namespace? I believe it would be useful to be across all namespaces.

**Comment by gracewehner** [comment]
Hi @Sohamdg081992, FYI. Could you please take a look when you get a chance? Thanks!

**Comment by abdullah248** [comment]
There is also a similar error with the oom alert.

**Comment by Sohamdg081992** [comment]
I will take a look into this.

**Comment by Sohamdg081992** [comment]
The alert has been fixed.
