### ISSUE TITLE
[BUG] Default prometheus configuration doesn't include kubelet, cadvisor or node jobs

### ISSUE THREAD

**Issue by EppO** [Azure/prometheus-collector#411]
When deploying AMA add-on with AKS, deployment is using a replicaSet. #249 added a hardcoded variable `@sendDSUpMetric` that bypasses entirely the "if" conditions blocks for kubelet, cadvisor and node exporter (issue highlighted as comment in code below):

```ruby
if currentControllerType == @replicasetControllerType
  if advancedMode == false
    UpdateScrapeIntervalConfig(@cadvisorDefaultFileRsSimple, cadvisorScrapeInterval)
    if !cadvisorMetricsKeepListRegex.nil? && !cadvisorMetricsKeepListRegex.empty?
      AppendMetricRelabelConfig(@cadvisorDefaultFileRsSimple, cadvisorMetricsKeepListRegex)
    end
    defaultConfigs.push(@cadvisorDefaultFileRsSimple)
  elsif @sendDSUpMetric == true # == if currentControllerType == "replicaset" && advancedMode == true && @sendDSUpMetric == true. but @sendDSUpMetric is ALWAYS false
    UpdateScrapeIntervalConfig(@cadvisorDefaultFileRsAdvanced, cadvisorScrapeInterval)
    defaultConfigs.push(@cadvisorDefaultFileRsAdvanced)
  end
  # no if-statement for currentControllerType == "replicaset" && advancedMode == true && @sendDSUpMetric == false. Whole block is doing nothing for that use case which is AMA AKS add-on's mode.
else
  if advancedMode == true && ENV["OS_TYPE"].downcase == "linux"
    UpdateScrapeIntervalConfig(@cadvisorDefaultFileDs, cadvisorScrapeInterval)
    if !cadvisorMetricsKeepListRegex.nil? && !cadvisorMetricsKeepListRegex.empty?
      AppendMetricRelabelConfig(@cadvisorDefaultFileDs, cadvisorMetricsKeepListRegex)
    end
    contents = File.read(@cadvisorDefaultFileDs)
    contents = contents.gsub("$$NODE_IP$$", ENV["NODE_IP"])
    contents = contents.gsub("$$NODE_NAME$$", ENV["NODE_NAME"])
    File.open(@cadvisorDefaultFileDs, "w") { |file| file.puts contents }
    defaultConfigs.push(@cadvisorDefaultFileDs)
  end
end
```

Hence, default scrape configs for kubelet, cadvisor and node jobs are **not** generated. All other components are not using `@sendDSUpMetric` variable and their default scrape configs get generated correctly.

**Comment by vishiy** [comment]
Those are scraped & sent from daemon set (not deployment). This is intended. Is that your question ?

**Comment by EppO** [comment]
🤦 I get my mistake now... I was looking at the generated config following these instructions https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/prometheus-metrics-troubleshoot, looking only at ama-metrics prometheus config, and not the ama-metrics-node-* ones. I get now that ama-metrics pod is a replicaset to scrape the pod and service metrics and the ama-metrics-node-* daemonset is taking care of the metrics exposed by daemonsets. 
Sorry about the hassle!

**Comment by vishiy** [comment]
No problems. i will close this. Please let us know if you have any more questions. Thanks for raising issues in our repo.

**Comment by gracewehner** [comment]
Thanks @EppO for pointing this out, we have added this clarification to our docs now: https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/prometheus-metrics-troubleshoot
