### ISSUE TITLE
Maximum allowed content length: 1048576 bytes (1 MB). Provided content length: 1175590 bytes

### ISSUE THREAD

**Issue by dineshkumar181094** [Azure/prometheus-collector#421]
Hi Team,

As far as I can understand the architecture there is a  collector service running that scrapes the target and pushes to the metric extension service which is running on port 55680.
Now, this metricsExtenstion service is doing a remote write to managed Prometheus.
I can see you have given [config](https://github.com/Azure/prometheus-collector/blob/main/otelcollector/metricextension/me.config) for the metricsExtention.
But the problem is now the managed Prometheus is not accepting payloads of more than 1 MB and metricExtention is trying to push more data and ultimately failing.
We need to fix this config mismatch by either providing support and more documentation on how to control metricExtention parameters I can see they are hard coded as of now.
I can contribute once the issue Is confirmed.

**Comment by dineshkumar181094** [comment]
--storage.remote.read-max-bytes-in-frame=1048576
              Maximum  number of bytes in a single frame for streaming remote read response types
              before marshalling. Note that client might have limit on frame size as well. 1MB as
              recommended by protobuf by default.
              
              We can see more evidence here.

**Comment by gracewehner** [comment]
Hi @dineshkumar181094, thanks for opening this issue and PR. Could you please confirm if you are seeing this only in the ama-metrics-node pods (the daemonset pods) or are you also seeing this in the ama-metrics replicaset pod?

**Comment by dineshkumar181094** [comment]
Hi @gracewehner, 
I'm only seeing the error logs in ama-metrics replica set pod.
ama-metrics-node (deamonset) is working fine.

**Comment by vishiy** [comment]
@dineshkumar181094 - Its all approximations, there is no guarantee we will be able to limit the size to 1MB or less. it could be 1.01 MB say for example. The fix for this is getting deployed on the service side , so it can be upto 4MB, and so our agent side approximations will continue to work.
