### ISSUE TITLE
Why create a Managed Resource Group, instead allow a choice for where resources are deployed

### ISSUE THREAD

**Issue by brwilkinson** [Azure/prometheus-collector#440]
As per this documentation: 
- https://learn.microsoft.com/en-Us/azure/azure-monitor/essentials/azure-monitor-workspace-overview

### problem
Having the new resource created with a random name goes against declarative deployment techniques and best practice.

### solution
When creating the monitor accounts, please either allow one of the following options:

- Allow to pre-create dataCollectionEndpointResource and dataCollectionRuleResource, then link them back to the account
- Allow the Managed Resource Group were the dataCollectionEndpointResource and dataCollectionRuleResource to be manually defined.

```bicep
resource monitorAccount 'Microsoft.Monitor/accounts@2021-06-03-preview' = {
  name: '${DeploymentURI}Monitor'
  location: resourceGroup().location
  properties: {
    #disable-next-line BCP037
    publicNetworkAccess: 'Enabled'
    defaultIngestionSettings: {
      dataCollectionEndpointResourceId: dataCollectorEPLinux.id
      dataCollectionRuleResourceId: dataCollectorEPLinuxRule.id
    }
  }
}
```

example of the current behaviour

- random "new" managed resource group

![image](https://user-images.githubusercontent.com/3605266/229210912-b51dfa90-37ea-458a-8ee6-440a7d38d195.png)

preferred way to do it

- Allow me to pre-deploy these other resources, then link them back to the account 
  - e.g. in the same Resource Group
  - e.g. with my chosen names for the resources

![image](https://user-images.githubusercontent.com/3605266/229211027-e15b0a83-e733-4464-93d9-cdd6af51b489.png)

**Comment by brwilkinson** [comment]
Also wondering why we have the new RP for this and it's not added to one of the following?
- https://learn.microsoft.com/en-us/azure/templates/microsoft.operationalinsights/allversions
- https://learn.microsoft.com/en-us/azure/templates/microsoft.insights/allversions

**Comment by brwilkinson** [comment]
Any comment on the feedback?

**Comment by brwilkinson** [comment]
Any chance someone can review, so this doesn't get closed without response?

**Comment by vishiy** [comment]
@brwilkinson - Azure monitor workspace team creates it when creating a workspace, to provision system DCRs, and that RG also has a deny assignment to prevent deletions & more. If you need more infor, pls ping me offline and we can chat .

**Comment by brwilkinson** [comment]
Thaks @vishiy

As I understand prometheus-collector it's the only resource using this new Monitor workspace at this time. 

The way it's being created is not ideal for Automation models, such as ARM/Bicep deployments.

If this doesn't get resolved early, it will be more problematic over time.
