### ISSUE TITLE
Prometheus Collector Fails Liveness Probe When Scraping Metrics from Flink TaskManager in Kubernetes

### ISSUE THREAD

**Issue by ksrMM** [Azure/prometheus-collector#579]
I am attempting to gather metrics from Flink running on a Kubernetes cluster. I've configured the setup using the flink-kubernetes-operator along with the Prometheus metricreporter. While I can successfully scrape metrics from the Job Manager, I encounter issues when trying to collect metrics from the TaskManager.

When the Prometheus collector attempts to scrape metrics from the TaskManager, it fails the liveness probe, causing the container to restart. For detailed error logs, please refer to [collector-log.txt](https://github.com/Azure/prometheus-collector/files/12486336/collector-log.txt).

Initially, I suspected that the issue might be due to insufficient memory resources. However, even after scaling up to higher node instances, the problem persists. The issue seems to be isolated to scraping metrics from the TaskManager, leading me to believe there may be a compatibility issue with Flink.

I've also tried using both static scrape configurations and pod annotations, but the issue remains unresolved.

Any guidance or suggestions would be greatly appreciated, especially since this is a managed service and I don't have much insight into its inner workings.

**Comment by vishiy** [comment]
hi what kubernetes distro is your cluster ? this component is supposed to be used only on aks and/or azure arc enabled kubernetes clusters. we have control plane rules that are needed to ingest data into azure and those will fail causing licenses issues .

**Comment by ksrMM** [comment]
I've set it up on AKS, following the provided documentation for installation and configuration.

**Comment by vishiy** [comment]
pls share your cluster id details at askazprom at microsoft and we will look our telemetry and get back .

**Comment by ksrMM** [comment]
Brief Summary for Others:
The issue stems from the high volume of metrics causing OOMKills. By selectively filtering to only the metrics we need, memory usage is reduced, leading to a stable and problem-free operation.
