### ISSUE TITLE
Prometheus collector with temporarily disconnected cluster

### ISSUE THREAD

**Issue by MagdaPaj** [Azure/prometheus-collector#583]
I have an Arc-enabled K8s cluster, and I enabled Prometheus metrics like described [here](https://learn.microsoft.com/en-us/azure/azure-monitor/containers/prometheus-metrics-from-arc-enabled-cluster?tabs=portal#onboard-from-container-insights).
I see a couple of ama-metrics pods with prometheus-collector running. What would happen if there were connectivity/bandwidth issues for an hour on the edge location? Would metrics be dropped, or stored locally for some time? Is there any configuration of it?

@vishiy, @gracewehner

**Comment by vishiy** [comment]
Hi @MagdaPaj  - apologies for delayed reponse. metrics would be dropped. we do not support disconnected scenarios now.
