### ISSUE TITLE
prometheus-collector keeps crashing with no_proxy setup in AKS

### ISSUE THREAD

**Issue by GerardoGR** [Azure/prometheus-collector#589]
When setting up an AKS cluster with a configuration similar to this:

```terraform
resource "azurerm_kubernetes_cluster" "aks" {
  # ...
  monitor_metrics {}

  http_proxy_config {
    https_proxy = "http://proxy-ip-address:port"
    no_proxy      = "localhost"
  }
  # ...
}
```

The **ama-metrics-node** pods keep crashing and show these logs:

```
******************Done Merging Default and Custom Prometheus Config*******************
prom-config-validator::No custom prometheus config found. Only using default scrape configs
prom-config-validator::Config file provided - /opt/defaultsMergedConfig.yml
prom-config-validator::Successfully generated otel config
prom-config-validator::Loading configuration...
prom-config-validator::Successfully loaded and validated prometheus config
prom-config-validator::Prometheus default scrape config validation succeeded, using this as collector config
prom-config-validator::Use default prometheus config: true
checking health of token adapter after 1 secs
checking health of token adapter after 2 secs
checking health of token adapter after 3 secs
checking health of token adapter after 4 secs
checking health of token adapter after 5 secs
checking health of token adapter after 6 secs
checking health of token adapter after 7 secs
checking health of token adapter after 8 secs
checking health of token adapter after 9 secs
checking health of token adapter after 10 secs
checking health of token adapter after 11 secs
checking health of token adapter after 12 secs
checking health of token adapter after 13 secs
checking health of token adapter after 14 secs
checking health of token adapter after 15 secs
checking health of token adapter after 16 secs
checking health of token adapter after 17 secs
checking health of token adapter after 18 secs
checking health of token adapter after 19 secs
checking health of token adapter after 20 secs
checking health of token adapter after 21 secs
checking health of token adapter after 22 secs
checking health of token adapter after 23 secs
checking health of token adapter after 24 secs
checking health of token adapter after 25 secs
checking health of token adapter after 26 secs
checking health of token adapter after 27 secs
checking health of token adapter after 28 secs
checking health of token adapter after 29 secs
checking health of token adapter after 30 secs
checking health of token adapter after 31 secs
checking health of token adapter after 32 secs
checking health of token adapter after 33 secs
checking health of token adapter after 34 secs
checking health of token adapter after 35 secs
checking health of token adapter after 36 secs
checking health of token adapter after 37 secs
checking health of token adapter after 38 secs
checking health of token adapter after 39 secs
checking health of token adapter after 40 secs
checking health of token adapter after 41 secs
checking health of token adapter after 42 secs
checking health of token adapter after 43 secs
checking health of token adapter after 44 secs
checking health of token adapter after 45 secs
checking health of token adapter after 46 secs
checking health of token adapter after 47 secs
checking health of token adapter after 48 secs
checking health of token adapter after 49 secs
checking health of token adapter after 50 secs
checking health of token adapter after 51 secs
checking health of token adapter after 52 secs
checking health of token adapter after 53 secs
checking health of token adapter after 54 secs
checking health of token adapter after 55 secs
checking health of token adapter after 56 secs
checking health of token adapter after 57 secs
checking health of token adapter after 58 secs
checking health of token adapter after 59 secs
checking health of token adapter after 60 secs
Connecting to proxy-ip-address:port (proxy-ip-address:port)
  HTTP/1.1 403 Forbidden
wget: server returned error: HTTP/1.1 403 Forbidden
giving up waiting for token adapter to become healthy after 61 secs
```

This suggest that wget is trying to go through the proxy even though `no_proxy` is seated up. We have also confirmed that this is the case by looking at the logs from the proxy directly.

Do you have a suggestion on how we can workaround this, or if there is a fix for this?

**Comment by GerardoGR** [comment]
> Hi @GerardoGR - This is a bug that we will be fixing. But this is just a check that logs the failures. Do you see crash looping ? If so, you need to  include IMDS IP list to no-proxy -- 169.254.169.254 . Let us know if that fixes crash looping. Also, are you using private/private-linked AKS clusters & AMPLS (azure monitor private link scope) ? 
> 
> Thanks for raising this issue.
> 

Hi @vishiy,
I highly appreciate the fast response.

Unfortunately, we do see Crash looping. I will add the IMDS IP to the no_proxy list as you mentioned and write here the result.

And yes, we are using a private AKS cluster with an AMPLs setup.

**Comment by vishiy** [comment]
ok thanks . for private links we recently updated our docs a few days back . basically you would also need to associate a dce with cluster . you can use the same dce as ingestion , if cluster and workspace are in same region. else you would need to create a new dce is clusters region and associate . please refer to our docs. and i also don’t think you would need to add imds up explicitly , as it’s being added internally .

**Comment by GerardoGR** [comment]
We have already the AMPLs and DCE setup as you mentioned. We know it is also working because we "patched" the prometheus-collector to remove the HTTP_PROXY env-var to force it to use the private-link and we were able to display the metrics in Grafana. As far as I've seen, the  IMDS IP address is not set automatically. I will double check and try to set it and get back here to post the result.

**Comment by GerardoGR** [comment]
I just checked, and it seems that the IMDS IP address (169.254.169.254) is in the no_proxy list... I will look for the updated docs, but if you happen to have them at hand, I would highly appreciate if you share them here please.

**Comment by vishiy** [comment]
Hi  @GerardoGR - here is link to latest doc -- 

https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/private-link-data-ingestion
https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/azure-monitor-workspace-private-endpoint

Also, we found the root cause for this proxy issue. we are making a fix and deploying it. it will fix the wget issue, which is also causing crashloops when proxy is enabled, due to clashing with liveness timing. For private links, please follow the above doc(s).

Our deployment to all regions with the fix will take 2-3 weeks . If you want the fix earlier, please share AKS subscriptions & regions where you are seeing this proxy issue and/or you are planning to deploy AKS clusters using proxy, and we will try to roll that out earlier just for your sub. If you are not comfortable sharing subid & regions here, you can also mail us at askazprom at microsoft with those details. @bragi92  fyi

**Comment by GerardoGR** [comment]
Hi @vishiy,
Those are great news!. Thank you for the speedy fix!
We would definitely prefer sharing such information via a direct channel (like email), therefore I will send the request to the email you shared.

Do you have a PR where I can checkout the branch?, maybe we can also try the changes directly by pushing and pulling the fixed docker image.

**Comment by GerardoGR** [comment]
Found it 🙂 https://github.com/Azure/prometheus-collector/pull/591

**Comment by vishiy** [comment]
Hi @GerardoGR - It will take up to 10 days to 2 weeks for our changes to go to WEU region. I saw your other email and hence want to confirm here.

**Comment by GerardoGR** [comment]
Hi @vishiy ,
Thank you for letting me know. Although from the previous comments, I understood that you could have rolled out the changes to our specific Subscription IDs sooner. But maybe I understood wrong.

**Comment by vishiy** [comment]
Hi @GerardoGR - unfortunately, we are unable to expedite just for your clusters, due to a different issue, and this is being rolledout  as regular release.

**Comment by vishiy** [comment]
Hi @GerardoGR - is this issue fixed for you, now ? Can you please let us know when you get a chance ? Thanks for your time.

**Comment by GerardoGR** [comment]
Hi @vishiy ,
Thanks for the followup. I have not had the chance to check if it is fixed, but I'll let you know as soon as a have another look

**Comment by vishiy** [comment]
Thank you!

**Comment by GerardoGR** [comment]
@vishiy sorry for the late reply, better late than never 😅 . But I can confirm that with the fix deployed in https://github.com/Azure/prometheus-collector/pull/591 the issue does not happen anymore.

Thanks for all the effort!
