### ISSUE TITLE
tls_config for the promethues-collector 

### ISSUE THREAD

**Issue by ktdharan** [Azure/prometheus-collector#598]
Hello , 

We have current scenario where would like to use the tls_config  to  use  CA certificate to validate API server certificate . For this we will  have to mount the certificates as volumes into the collector  pod and use them as part of the ama-metrics-prometheus-config-configmap . 

Is there a way to accomplish this? Not sure about the approach as we know the Prometheus collector get deployed automatically when the monitoring metrics profile is enabled.

**Comment by ktdharan** [comment]
@vishiy  -> Please do let us know if you have any suggestions

**Comment by vishiy** [comment]
@ktdharan , you can use the below config in your scrape job, if you want to use api server cert for the cluster. As you can see its already mounted into our pod, which you can reference from the below path.

` tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true`

We are starting to work on providing the ability to bring in custom certs to use for scrape. it will take a while for us to get it out. - @Sohamdg081992 fyi

Please let us know if you need anything more on this.

**Comment by ktdharan** [comment]
@vishiy -> we are not using the default cluster certificates because of security requirements. is there a short-term solution from which we can mount the certificates, because we really need this for our scraping custom metrics

**Comment by vishiy** [comment]
Hi @ktdharan - which cert are you refering to ? is it ca cert or cert for client auth ? https://prometheus.io/docs/prometheus/latest/configuration/configuration/#tls_config

**Comment by ktdharan** [comment]
@vishiy -> ca cert

**Comment by ktdharan** [comment]
@vishiy -> any update

**Comment by Sohamdg081992** [comment]
Hi @ktdharan , I am working on this feature currently and it's in the design phase. I will try to get this out by end of next week.

**Comment by ktdharan** [comment]
@Sohamdg081992 -> is there an update from your side ?

**Comment by Sohamdg081992** [comment]
> @Sohamdg081992 -> is there an update from your side ?

Hi @ktdharan, the design was completed on Oct 11 and I am working on the implementation now. I am trying to get it out by the end of this month.

**Comment by ktdharan** [comment]
@Sohamdg081992 -> Thank you so much

**Comment by ktdharan** [comment]
@Sohamdg081992 -> will this have the capability also mounting the custom secrets? because the scrape cofigs will be authenticated

**Comment by ktdharan** [comment]
@Sohamdg081992  -> Any Update ?

**Comment by Sohamdg081992** [comment]
@ktdharan , I am testing the changes now on my cluster. I am facing some issues, I will keep you posted on this. Thanks!

**Comment by ktdharan** [comment]
@Sohamdg081992  -> Do we have an update one the request

**Comment by Sohamdg081992** [comment]
@ktdharan I have the changes mostly ready. I will make a PR today/tomorrow and will merge early next week after our bug bash. But this feature will only be available to public in January because of Code Freeze (CCOA) for the holiday season.

**Comment by ktdharan** [comment]
@Sohamdg081992  -> do we have a date when this would be available in Jan? we would like to plan this activity based on that

**Comment by ktdharan** [comment]
@Sohamdg081992 @vishiy  -> Is this already rolled out? we would like to test these changes as early as possible

**Comment by ktdharan** [comment]
> @Sohamdg081992 @vishiy -> Is this already rolled out? we would like to test these changes as early as possible

is this already rolled out?
