### ISSUE TITLE
Running the az cli commands to enable prometheus metrics seems to have westeurope statically defined in the naming

### ISSUE THREAD

**Issue by akata72** [Azure/prometheus-collector#603]
I have my Azure Monitor workspace and AKS cluster deployed in **norwayeast**. 

When I run the command to enable monitoring and associate this workspace to the cluster;

`az aks update --enable-azure-monitor-metrics -n $clusterName -g $clusterResourceGroupName --azure-monitor-workspace-resource-id $workspaceResourceId`

It creates the dataCollectionEndpoint and datacollectionRules with westeurope in the name (but in the right location). 
![image](https://github.com/Azure/prometheus-collector/assets/16230163/2d96d87b-ff06-4a9b-8d0b-6a3774405da7)

I would expect the location to be retrieved from where the Azure monitor workspace is actually located (like in the bicep templates).

**Comment by vishiy** [comment]
hi thanks for raising this . what region is your resource group in ?

**Comment by akata72** [comment]
The RG is in norwayeast (the cluster and azure monitor account as well).

**Comment by vishiy** [comment]
Hi - i Just checked, and we have a mapping that we use for naming and that has westeurope. We will update the mappings as part of newly added regions soon. Thanks for reporting this issue.

**Comment by vishiy** [comment]
Hi - we have a fix for this that will rollout in a few weeks. Thanks for reporting this.
