### ISSUE TITLE
invalid Azure Monitor Workspace Resource Id error

### ISSUE THREAD

**Issue by cchapin2020** [Azure/prometheus-collector#656]
When I try to deploy the Bicep FullAzureMonitorMetricsProfile.bicep template using the command in the readme, I am receiving an error:
Inner Errors: 
{"code": "InvalidAzureMonitorWorkspaceResourceId", "message": "'/subscriptions/subid/resourcegroups/rg/providers/microsoft.operationalinsights/workspaces/workspace name' seems like an invalid Azure Monitor Workspace Resource Id. It should be like '/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/my-resource-group/providers/microsoft.monitor/accounts/my-azure-monitor-workspace'"}

I checked all of the Log Analytics Workspaces in my subscription and all of them are in /providers/microsoft.operationalinsights/workspaces and not /providers/microsoft.operationalinsights/accounts

Am I missing something or is this an issue that needs to be addressed with support?

**Comment by cchapin2020** [comment]
I found that the log analytics workspace has to be created from Azure Monitor to get this naming convention. Is there a way to use a LA workspace that is created from the Log Analytics Service??

**Comment by gracewehner** [comment]
Hi @cchapin2020, the Azure Monitor workspace is the new workspace for storing metrics and Azure Monitor data (and eventually will be for logs too). It is separate from the Log Analytics workspace. Please see [here](https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/azure-monitor-workspace-overview) for an overview and [here](https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/azure-monitor-workspace-manage?tabs=azure-portal#create-an-azure-monitor-workspace) for how to create one.

Please also let us know if there's anything we can add to make this distinction more clear in the future!
