### ISSUE TITLE
livenessprobe.cmd does not work as expected.

### ISSUE THREAD

**Issue by AbelHu** [Azure/prometheus-collector#675]
In https://github.com/Azure/prometheus-collector/blob/main/otelcollector/build/windows/scripts/livenessprobe.cmd, `exit /b 1` does not set the exit code to 1 after `if errorlevel 1`.

Below works:
```
            if errorlevel 1 (
                echo "Metrics Extension is not running (configuration exists)"
                exit
            )
```

**Comment by vishiy** [comment]
Thanks @AbelHu for reporting this. We will fix this.

**Comment by vishiy** [comment]
we found the issue, its due to errorlevel not being returned correctly.

**Comment by AbelHu** [comment]
@vishiy I am curious why you do not use `exit $exitcode` directly. In the main branch, it seems like that both `exit /b 1` and `goto eof` are used and it may be difficult for readers to understand and add code later.

**Comment by vishiy** [comment]
exit from inner blocks with delayed expansion has issues is what we tested and found out. So just a simple jump out and exit on a small block is not bad.

**Comment by AbelHu** [comment]
Per my result, `exit 1` should always work so I am not sure whether changing all `exit /b 1` to `exit 1` is better.

**Comment by joshuadmatthews** [comment]
@vishiy Hi, what was the fix here? I am getting this error on my AKS cluster right now.

**Comment by vishiy** [comment]
@joshuadmatthews - If you are seeing restarts due to "metrics extension not running (config not found)", it might be due to other issues as well, for not being able to download config - like data collection rules deleted, private link not configured properly etc... Is any of that true for your cluster ?

**Comment by joshuadmatthews** [comment]
No on the whole cluster is fine, everything was great until I enabled Prometheus. Cluster is still fine, but the Prometheus-collector is restarting non stop as mentioned.

**Comment by bragi92** [comment]
Hey @joshuadmatthews can you email your cluster details (cluster resource id) to  ' c i p r o m e t h e u s [ a t ] m i c r o s o f t [ d o t ] c o m ' ?

I can take a look at our telemetry to figure out what is going one with it.
