### ISSUE TITLE
Scrapping Metrics from Authenticated Endpoints  

### ISSUE THREAD

**Issue by ktdharan** [Azure/prometheus-collector#708]
As an user of managed Prometheus , is there a possibility of scraping data from authenticated endpoints ? if so how can that be achieved.

**Comment by ktdharan** [comment]
@vishiy -> Do you have any idea ?

**Comment by vishiy** [comment]
Hi - we are waiting on current (jan) deployment to go thru and this will be in feb deployment hopefully.

**Comment by ktdharan** [comment]
@vishiy -> Do we have an date for the release ?
