### ISSUE TITLE
recommendedMetricAlerts throws Property name: Rules.Count, Attempted value: 40, Error: 'Rules Count' must be between 1 and 20. You entered 40. Activity ID: fa7d4520-dfe5-4b1a-81dc-75018f0b5f8d. (Code: BadRequest)

### ISSUE THREAD

**Issue by uBoscuBo** [Azure/prometheus-collector#742]
Hi,

I am trying to deploy the recommended alerts that are mentioned [here](https://github.com/Azure/prometheus-collector/blob/main/GeneratedMonitoringArtifacts/Default/recommendedMetricAlerts.json) through the Custom Deployment resource on Azure. When deployed, I get the following error.

> Property name: Rules.Count, Attempted value: 40, Error: 'Rules Count' must be between 1 and 20. You entered 40. Activity ID: fa7d4520-dfe5-4b1a-81dc-75018f0b5f8d. (Code: BadRequest).

Does anyone know what this means? 

Steps to Reproduce:

> 1.  Download the recommendMetricAlerts
> 2. Log into the Azure Portal
> 3. Redirect to "Deploy a Custom Template"
> 4. Click "Build your own template in the editor."
> 5. "Load file"
> 6. Choose the downloaded file.
> 7. Click "Save"
> 8. Fill in the Project Details and Instance Detail
> 9. Click Review + Create

**Comment by vishiy** [comment]
Hi @uBoscuBo - known issue . @Sohamdg081992 is working on a fix .

**Comment by Sohamdg081992** [comment]
The template is fixed now with the categories. Closing this issue.

**Comment by uBoscuBo** [comment]
@Sohamdg081992 - Thanks mate! If you don't mind sharing, what was the issue? Just out of curiosity.

**Comment by uBoscuBo** [comment]
@Sohamdg081992 - Thanks mate. FYI - you are missing a ")" parenthesis at the end of line 817.
