### ISSUE TITLE
label_limit exceeded (metric: kafka_controller_ActiveBrokerCount_Value, number of labels: 73, limit: 63

### ISSUE THREAD

**Issue by zhangchl007** [Azure/prometheus-collector#775]
Hi team
I had enabled pod monitor for kafka cluster, but it does not work due to label, according to the configuration of Managed Prometheus,
I guess it caused by the specify setting below. Could you please help me on this issue.

- separator: ;
    regex: __meta_kubernetes_pod_label_(.+)
    replacement: $1
    action: labelmap

![image](https://github.com/Azure/prometheus-collector/assets/13577471/3779e145-cc36-4341-ac07-9a3d815f1de1)

**Comment by vishiy** [comment]
Hi @zhangchl007 - We inject constraints as our backend has limits for number of labels per time-series . Please see them doc-ed here - https://learn.microsoft.com/en-us/azure/azure-monitor/containers/prometheus-metrics-troubleshoot#metric-names-label-names--label-values. If they are exceeded, we just fail the scrape job saying the reason (like your screen shot says)

As the error says, we allow 63 labels but some of your time-series we are scraping have 73 labels in it. Please use `labeldrop` thru relabeling to drop atleast 10 labels to bring the number of labels to 63 for one of the kafka metrics thats shown in the error.

**Comment by zhangchl007** [comment]
@Vishiy, Actually, I had deployed the labeldrop, which doesn't work, maybe there is an issue, I just paste here for you reference.
cat ama-metrics-prometheus-config.yaml
apiVersion: v1
data:
  prometheus-config: |-
    global:
      scrape_interval: 10s
    scrape_configs:
      - job_name: "kafka-pods"
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_container_name]
            action: keep
            regex: kafka
          - source_labels:
              [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            separator: ":"
            regex: ([^:]+)(?::\d+)?
            target_label: __address__
            replacement: ${1}:${2}
            action: replace
          - action: labeldrop
            regex: __meta_kubernetes_pod_annotation.*
      - job_name: "cilium-pods"
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_container_name]
            action: keep
            regex: cilium-agent
          - source_labels:
              [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            separator: ":"
            regex: ([^:]+)(?::\d+)?
            target_label: __address__
            replacement: ${1}:${2}
            action: replace
          - source_labels: [__meta_kubernetes_pod_node_name]
            action: replace
            target_label: instance
          - source_labels: [__meta_kubernetes_pod_label_k8s_app]
            action: replace
            target_label: k8s_app
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            regex: (.*)
            target_label: pod
          - action: labeldrop
            regex: __meta_kubernetes_pod_annotation.*
        metric_relabel_configs:
          - source_labels: [__name__]
            action: keep
            regex: (.*)
kind: ConfigMap
metadata:
  name: ama-metrics-prometheus-config
  namespace: kube-system

**Comment by vishiy** [comment]
Hi - do you see errors on the target ux now ? If you see errors please share them here. If no errors, can you share your AMW (workspace resource id) ? If you don't want to share here, please email ciprometheus  a-t   m-i-c-r-o-s-o-f-t   c-o-m

**Comment by zhangchl007** [comment]
@vishiy  I had sent the email to you for this issue, Thanks!

**Comment by zhangchl007** [comment]
@vishiy  we have to fix this issue, I export the configuration from ama as your reference:
`global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 1m
  label_limit: 80
scrape_configs:
- job_name: kube-apiserver
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: https
  label_limit: 63
  label_name_length_limit: 511
  label_value_length_limit: 1023
  authorization:
    type: Bearer
    credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: true
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
    separator: ;
    regex: default;kubernetes;https
    replacement: $1
    action: keep
  kubernetes_sd_configs:
  - role: endpoints
    kubeconfig_file: ""
    follow_redirects: true
    enable_http2: true
- job_name: kube-state-metrics
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  label_limit: 63
  label_name_length_limit: 511
  label_value_length_limit: 1023
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - ama-metrics-ksm.kube-system.svc.cluster.local:8080
- job_name: kubernetes-pods
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  label_limit: 63
  label_name_length_limit: 511
  label_value_length_limit: 1023
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
    separator: ;
    regex: "true"
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
    separator: ;
    regex: (.+)
    target_label: __metrics_path__
    replacement: $1
    action: replace
  - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
    separator: ;
    regex: ([^:]+)(?::\d+)?;(\d+)
    target_label: __address__
    replacement: $1:$2
    action: replace
  - separator: ;
    regex: __meta_kubernetes_pod_label_(.+)
    replacement: $1
    action: labelmap
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: kubernetes_namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: kubernetes_pod_name
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: kafka
    replacement: $1
    action: keep
  kubernetes_sd_configs:
  - role: pod
    kubeconfig_file: ""
    follow_redirects: true
    enable_http2: true
- job_name: kafka-pods
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  label_limit: 63
  label_name_length_limit: 511
  label_value_length_limit: 1023
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_container_name]
    separator: ;
    regex: kafka
    replacement: $1
    action: keep
  - source_labels: [address, __meta_kubernetes_pod_annotation_prometheus_io_port]
    separator: ':'
    regex: ([^:]+)(?::\d+)?
    target_label: address
    replacement: ${1}:${2}
    action: replace
  - separator: ;
    regex: __meta_kubernetes_pod_annotation_(.+)
    replacement: $1
    action: labeldrop
  kubernetes_sd_configs:
  - role: pod
    kubeconfig_file: ""
    follow_redirects: true
    enable_http2: true
- job_name: cilium-pods
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  label_limit: 63
  label_name_length_limit: 511
  label_value_length_limit: 1023
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_container_name]
    separator: ;
    regex: cilium-agent
    replacement: $1
    action: keep
  - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
    separator: ':'
    regex: ([^:]+)(?::\d+)?
    target_label: __address__
    replacement: ${1}:${2}
    action: replace
  - source_labels: [__meta_kubernetes_pod_node_name]
    separator: ;
    regex: (.*)
    target_label: instance
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_label_k8s_app]
    separator: ;
    regex: (.*)
    target_label: k8s_app
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: pod
    replacement: $1
    action: replace
  metric_relabel_configs:
  - source_labels: [__name__]
    separator: ;
    regex: (.*)
    replacement: $1
    action: keep
  kubernetes_sd_configs:
  - role: pod
    kubeconfig_file: ""
    follow_redirects: true
    enable_http2: true
`

**Comment by vishiy** [comment]
closing as fixed as per @zhangchl007's email.
