### ISSUE TITLE
What's the difference between "controlplane-apiserver" and "apiserver" targets

### ISSUE THREAD

**Issue by kamilzzz** [Azure/prometheus-collector#863]
By default, `controlplane-apiserver` target is enabled but `apiserver` is not.
What's the difference between these two?

With the default config I treid to query using PromQL for metrics collected from `controlplane-apiserver` target (https://learn.microsoft.com/en-us/azure/azure-monitor/containers/prometheus-metrics-scrape-configuration-minimal#:~:text=node_uname_info%22-,controlplane%2Dapiserver,-apiserver_request_total) but looks like all of them were empty.

**Comment by bragi92** [comment]
Hi @kamilzzz We're currently in public preview for the monitoring control plane metrics and you can read about it here : https://learn.microsoft.com/en-us/azure/aks/monitor-control-plane-metrics

You will have to enable a feature flag for those metrics to be present as described in the documentation. Once this feature goes out of preview into being Generally Available we will be deprecating the older apiserver target as these are being scraped from your clusters nodes in lieu of the metrics being scrapped directly from the infrastructure nodes of the control plane of your cluster (i.e. the `controlplane-apiserver` target)

**Comment by kamilzzz** [comment]
Thanks @bragi92, makes sense 😊
