### ISSUE TITLE
KubeContainerOOMKilledCount never resolves because relies on terminated reason

### ISSUE THREAD

**Issue by yene** [Azure/prometheus-collector#888]
hi,

the rule KubeContainerOOMKilledCount keeps being active as long as the pod has `containerStatuses.lastState.terminated.reason` OOMKilled.

is this intended behaviour? Should the metric not exclude pods that are healthy again after some time.

thank you for your time

```
sum by (cluster,container,controller,namespace)(kube_pod_container_status_last_terminated_reason{reason="OOMKilled"} * on(cluster,namespace,pod) group_left(controller) label_replace(kube_pod_owner, "controller", "$1", "owner_name", "(.*)")) > 0
```

**Comment by vishiy** [comment]
Hi @yene - Thanks for reporting. So are you saying if there is a container that *was* OOMkilled at some point, and then its running fine now, but the alert is active as its looking at *last* state being oomkilled ?

**Comment by yene** [comment]
@vishiy correct. As an end result we have lots of Azure Alerts that are open.

**Comment by vishiy** [comment]
ok, thank you. We get the issue, and will update to a different query. will keep this issue open to track. Thanks for reporting this.

**Comment by vishiy** [comment]
@yene - closing this as per our email conversation, as this is the oss convention.

**Comment by yene** [comment]
this problem is not solved
