### ISSUE TITLE
How to ignore kube-system namespace for KubePodContainerRestart

### ISSUE THREAD

**Issue by yene** [Azure/prometheus-collector#902]
**Problem**
We configured the recommended alerts, the KubePodContainerRestart triggers quite often because services in kube-system restart.

Is it possible for KubePodContainerRestart to ignore kube-system (or other namespaces)?

**Comment by bragi92** [comment]
Hi @yene, Yes you can edit the query to exlude the kube-system namespace. For the KubePodContainerRestart query it would look something like this :

```
sum by (namespace, controller, container, cluster)(
  increase(kube_pod_container_status_restarts_total{job="kube-state-metrics", namespace!="kube-system"}[1h]) 
  * on(namespace, pod, cluster) 
  group_left(controller) 
  label_replace(kube_pod_owner{namespace!="kube-system"}, "controller", "$1", "owner_name", "(.*)")
) > 0
```

**Comment by bragi92** [comment]
Hi @yene Can you also let us know which pods that are continuously restarting? Is it any of the ama-metrics-* pods or some other pods?

**Comment by yene** [comment]
k8s: 1.29.2
They are not continuously restarting, just from time to time. Not enough to care for a pattern, but too much for alarm fatique.
metrics-server and sometimes coredns-autoscaler

**Comment by bragi92** [comment]
Alright, thanks for the info. Closing this issue.

**Comment by bragi92** [comment]
Its possible you might miss some alerts for any kube-system pods that are getting restarted continusly.

@yene Do you have any ideas on how to handle this? Maybe segregrate kube-system pods in a different alerting rule group so that they don't cause alarm fatigue?

**Comment by bragi92** [comment]
Closing issue as no action item left on this.
