### ISSUE TITLE
Missing step in AddonTerraformTemplate

### ISSUE THREAD

**Issue by iohenkies** [Azure/prometheus-collector#942]
Hi all,

For the below we already had a support ticket at Microsoft. Their conclusion was that there are no issue with the Azure backplane regarding this specific issue, and it should be a problem in the code. They reproduced our situation, and had the exact same results.

**The issue**
We're setting up managed Prometheus on some of our private AKS clusters, using the code provided here:
https://github.com/Azure/prometheus-collector/tree/main/AddonTerraformTemplate

It seems to be missing one essential step, or in any case it doesn't work: the data collection endpoint and data collection rule aren't properly linked (I believe this is called the data collection rule association). See screenshot.

When this is not set properly, managed Prometheus is not working, and the ama-metrics pods on the cluster keep crashing.

We've tested this in different subscriptions with different clusters, with different versions of the Azure TerrAform providers even, the results are always the same. So there seems to be a step missing, in the code, Terraform provider, a combination of those, or something else. As said, the Microsoft support team had the same results with the same code.

When we **manually select and save the proper endpoint**, managed Prometheus starts working and pods stop crashing. We need to do this via the Terraform code though, and not manually.

Any help and input is greatly appreciated.

Thanks and regards!
![comm_issue](https://github.com/user-attachments/assets/e867bba1-f853-494a-950f-01865bd217fa)

**Comment by Sohamdg081992** [comment]
@iohenkies , just to confirm , the clusters are private linked clusters, right?

**Comment by iohenkies** [comment]
@Sohamdg081992 that's correct and probably good to add to the original issue. I'll add it.

**Comment by Sohamdg081992** [comment]
@iohenkies Thanks! We are working on updating our docs to point to the private link setup after onboarding addon.

**Comment by iohenkies** [comment]
@Sohamdg081992 thanks. Does this mean that it is not possible to setup via code (in the same Terraform run), and that you always need to do the manual step afterwards, or am I misunderstanding?

**Comment by iohenkies** [comment]
Hi @Sohamdg081992, could you please clarify the above?

**Comment by Sohamdg081992** [comment]
@iohenkies we have added a [task ](https://msazure.visualstudio.com/InfrastructureInsights/_sprints/taskboard/Prometheus-agent/InfrastructureInsights/Dilithium/CY24Q3/Monthly/07%20Jul%20(Jul%2001%20-%20Jul%2031)?workitem=28853404) in our sprint to add the Terraform setup code for private linked clusters and will work on it.

**Comment by iohenkies** [comment]
Thanks a lot, this was unclear to me. Will await an update.

**Comment by iohenkies** [comment]
Still relevant. Devs are working on it or will be working on it.

**Comment by Sohamdg081992** [comment]
@iohenkies I just created a [PR ](https://github.com/Azure/prometheus-collector/pull/958)to add the step. The PR  description has all the screenshots of the linking. Please feel free to test with this update and let me know if this works for you.

**Comment by iohenkies** [comment]
Great @Sohamdg081992 ! Will test this week.

**Comment by Sohamdg081992** [comment]
@iohenkies Thanks! Please feel free to test with the latest update in the [PR](https://github.com/Azure/prometheus-collector/pull/958). I made a commit today to create new DCE, if the cluster and workspace regions do not match.

**Comment by Sohamdg081992** [comment]
@iohenkies did you get a chance to test the template?

**Comment by iohenkies** [comment]
My sincere apologies @Sohamdg081992, there have been some production outages last week. I will test it this week for sure.

**Comment by Sohamdg081992** [comment]
Thanks @iohenkies !

**Comment by iohenkies** [comment]
Hi @Sohamdg081992, sorry for the delay.

With part of your code I was able to finally fix this for **existing** deployments. New deployments don't work yet. Let me explain a bit more about our environment.

For Terraform we're using a multi-level setup as explained below:
https://dev.to/piotrgwiazda/main-module-approach-for-handling-multiple-environments-in-terraform-1oln

This separates environments and creates separate statefiles per environment.

To visualize, this is our directory structure:
![tree](https://github.com/user-attachments/assets/57654aa9-066b-4a0f-a66b-6d9ad025c645)

Also important to know is that we can only deploy in a single region (company policy).

This being said, you can see that we can't use your code as provided. We need to move code around, make modules scalable, variablize all parts in the module and move them to the `main` or `env` directory, etc.

I'm providing you with this background, because the code as-is didn't work for us, but that might be because of the way we structured it. Finally the trick for existing deployment for us was to add this code in our module, which you provided:

```
resource "azurerm_monitor_data_collection_endpoint" "dce_privatelink" {
  kind                          = var.dcedcr_kind
  location                      = var.region
  name                          = var.msprom_privatelink_name
  resource_group_name           = var.resource_group_name
  public_network_access_enabled = var.public_network_access_enabled
  tags                          = local.common_tags
}

resource "azurerm_monitor_data_collection_rule_association" "dcra_privatelink" {
  data_collection_endpoint_id = azurerm_monitor_data_collection_endpoint.dce_privatelink.id
  target_resource_id          = var.cluster_id
  depends_on = [
    azurerm_monitor_data_collection_endpoint.dce,
    azurerm_monitor_data_collection_rule.dcr,
  ]
}
```

All variables come from `main` or `env`.

As you can see, we removed the counts and simplified the `data_collection_endpoint_id`. Adding the count provided us with a couple of errors, such as that count.index has to be provided to the `dcra_privatelink` and finally I could not come up with a reason why it should be provided at all. But maybe I'm wrong?

Also, the `useAzureMonitorPrivateLinkScope` should be declared somewhere, which now didn't happen in the code. But once again, this could just as easily be caused by our code structure.

Anyway, this works perfectly for the existing environments. It associates the `dcr` with the `dce`, metrics start flowing, pods stop crashing. Unfortunately though, a brand new environment does not result in a working Managed prometheus via private link. Tomorrow I can do more troubleshooting.

**Comment by iohenkies** [comment]
Time was limited today and unfortunately I did not book any significant progress.

So the issue remains as it was yesterday: existing deployments can be altered with this code to create a working managed Prometheus via private endpoints. A complete new environment with this code results in no metrics (e.g. 'The query returned no results.' in the Prometheus explorer).

Could you expand a bit more on the options I took out now because Terraform was not able to apply with these options? So the counts in the different block and the useAzureMonitorPrivateLinkScope variable? What should be the default here?

**Comment by Sohamdg081992** [comment]
@iohenkies I am unable to repro the issue for new setup. It is probably due to the multi-level setup. I was able to create a new deployment (cluster, DC objects, etc) with the code in the [PR ](https://github.com/Azure/prometheus-collector/pull/958) and have attached the screenshots for the new cluster creation. Can you please give more details on the error you are seeing for new environments.

The first resource is azurerm_monitor_data_collection_endpoint named private_link_dce. This resource creates a data collection endpoint for Azure Monitor. The count attribute is used to conditionally create this resource based on two conditions: whether the: The useAzureMonitorPrivateLinkScope  variable is true and whether the location of the Kubernetes cluster is different from the location of the Azure Monitor workspace. If both conditions are met, the resource is created; otherwise, it is not. 

The second resource is azurerm_monitor_data_collection_rule_association named dcraprivatelink. This resource associates a data collection rule with a target resource, in this case, the Kubernetes cluster. The count attribute conditionally creates this resource based on the useAzureMonitorPrivateLinkScope  variable. The data_collection_endpoint_id attribute sets the ID of the data collection endpoint to be used. If the Kubernetes cluster's location matches the Azure Monitor workspace's location, it uses the default endpoint (azurerm_monitor_data_collection_endpoint.dce.id); otherwise, it uses the private link endpoint (azurerm_monitor_data_collection_endpoint.private_link_dce.id). The target_resource_id attribute specifies the ID of the Kubernetes cluster. The depends_on attribute ensures that this resource is created only after the specified dependencies are created.

**Comment by iohenkies** [comment]
Thanks @Sohamdg081992. I will start working on this next week on our next sprint and report back ASAP. Is there a possibility to contact you more directly, e.g. via Email, Slack or Discord? Only for this issue of course. If not, we'll just use this issue.

**Comment by Sohamdg081992** [comment]
@iohenkies yes please contact me directly over email sohdasgupta@microsoft.com.

**Comment by iohenkies** [comment]
Much appreciated. Will work on this the coming week.

**Comment by iohenkies** [comment]
This is not entirely resolved IMHO. There are some follow-up questions that I emailed @Sohamdg081992 about on 29-08 and 04-09. It would be nice if we could tackle those.

**Comment by iohenkies** [comment]
Unfortunately still some unanswered questions.

**Comment by iohenkies** [comment]
Still relevant. Emailed again 27-09.

**Comment by bragi92** [comment]
@iohenkies Sorry for the delay. I'm taking over this issue but unfortunately I do not have the questions that you had sent to Soham. Can you please send the email to  `c i p r o m e t h e u s [ a t ] m i c r o s o f t [ d o t ] c o m`?

**Comment by iohenkies** [comment]
Thanks @bragi92. I will email you today.

**Comment by bragi92** [comment]
Hi @iohenkies I have replied to your email and also created a [PR](https://github.com/Azure/prometheus-collector/pull/991) to merge in support for private clusters in terraform. Please let me know if there is anything else I can help with on this issue?

**Comment by iohenkies** [comment]
Hi @bragi92. I was able to respond to your email, and provide our code.

As said, it does work now, which is great, but some things are not clear, mainly about the resources created that seem to not actually be used and if and what uses our AMPLS. Details are in the email. Thanks again.

**Comment by bragi92** [comment]
Hi @iohenkies , responded with details on how to check if ampls is being used and if it isn't then how to correct it.

**Comment by iohenkies** [comment]
This is finally solved and now all 100% clear and in code! Many thanks for all the help.
